# Generated by Django 4.2 on 2023-04-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanielApp', '0003_employee_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VenueName', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('ZipCode', models.IntegerField()),
                ('ContactPhone', models.IntegerField()),
                ('WebAddress', models.CharField(max_length=50)),
                ('EmailAddress', models.CharField(max_length=50)),
            ],
        ),
    ]
